Added Core SE version of vendor DV8 [REVPI-3018]
RevolutionPi/revpi-hat-data pull request #8
Opened 2023-02-21 14:30 UTC by hjokunbus

The device description has to be added in order to use HAT EEPROM of DV8's version of Core SE properly.

2023-02-21 14:58 UTC, iluminat23 commented
Should we add the Vendor to the README.md? Now we have different RevPi Core SE 8GB in the list.

2023-02-21 15:00 UTC, iluminat23 commented
And since we don't use symlinks anymore we have a hard time to actually see which configs are the same.

2023-02-21 16:51 UTC, nbuchwitz requested changes

2023-02-21 16:51 UTC, nbuchwitz commented on README.md
> +| [RevPi Core SE 8GB](./revpi-hat-PR100375R00.json) | PR100365 | R00 | 1 | revpi-core-se-2022 |
```suggestion
| [RevPi Core SE 8GB (OEM DV8)](./revpi-hat-PR100375R00.json) | PR100365 | R00 | 1 | revpi-core-se-2022 |
```

2023-02-21 16:51 UTC, nbuchwitz commented on revpi-hat-PR100375R00.json
> +    "pstr": "RevPi Core SE 8GB",
```suggestion
    "pstr": "RevPi Core SE 8GB (OEM DV8)",
```

2023-02-21 16:51 UTC, nbuchwitz commented on revpi-hat-PR100375R00.json
> +    "vstr": "DV8 PRODUCTS INC.",
```suggestion
    "vstr": "DV8 Energy",
```

2023-02-22 15:42 UTC, nbuchwitz approved these changes

2023-02-23 06:14 UTC, merged